# Generated by Django 2.0 on 2019-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20191021_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_K',
            field=models.CharField(max_length=125, null=True, verbose_name='K. 其他'),
        ),
    ]
