# Generated by Django 2.0 on 2019-10-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20191021_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigateuserinfo',
            name='user_speical_human',
            field=models.CharField(choices=[(0, '残疾人'), (1, '孕妇'), (2, '儿童'), (3, '65岁以上老人'), (10, '否')], default=10, max_length=50, null=True, verbose_name='特殊人群'),
        ),
    ]
